# GENERATED BY KOMAND SDK - DO NOT EDIT
from setuptools import setup, find_packages


setup(name="ipqualityscore-ipqs-plugin",
      version="1.0.0",
      description="IPQS Fraud and Risk Scoring connector provides enterprise grade fraud prevention, risk analysis, and threat detection.",
      author="ipqs",
      author_email="",
      url="",
      packages=find_packages(),
      install_requires=['insightconnect-plugin-runtime'],  # Add third-party dependencies to requirements.txt, not here!
      scripts=['bin/icon_ipqualityscore']
      )
